name: Fake action that simulates a deploy

on:
    workflow_dispatch:
        inputs:
            num:
                type: number
                required: true

concurrency:
    group: stage-deploy-${{github.event.inputs.num}}
    cancel-in-progress: true

jobs:
    deploy-stage:
        name: Deploy changes to stage
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: |
                  echo "Deploying to stage..."
                  sleep 2m
                  echo "Deploy completed"
