name: Fake action that simulates destroying an environment

on:
    workflow_dispatch:
        inputs:
            num:
                type: number
                required: true

concurrency:
    group: stage-deploy-${{github.event.inputs.num}}
    cancel-in-progress: true

jobs:
    destroy-stage:
        name: Destroys an environment
        runs-on: ubuntu-latest
        steps:
            - name: Destroy
              run: |
                  echo "Destroying environment to stage..."
                  sleep 0.5m
                  echo "Resources destroyed"
